name: NodeJS 

on:
    # Trigger the workflow on push,
    # but only for the pre-production branch
    push:
        branches:
            - main
env:
    AWS_REPOSITORY_URL: ${{ secrets.AWS_REPOSITORY_URL }}
    GITHUB_TOKEN: ${{ secrets.AWS_GITHUB_TOKEN }}

jobs:
    NodeJs:
        runs-on: ubuntu-latest

        steps:
             - name: configure The IAM cred
               uses: aws-actions/configure-aws-credentials@v1
               with:
                 aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_id }}
                 aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                 aws-region: us-east-1

             - name: Login in to Amazon ECR
               id: login-ecr
               uses: aws-actions/amazon-ecr-login@v1  
             
             - uses: actions/checkout@v2
             - name: SER ENV
               run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV

             - name: Build the Docker image
               run: |
                  docker build -t 180169423799.dkr.ecr.us-east-1.amazonaws.com/demo-project:$GITHUB_REF_NAME-$GITHUB_SHA . 
                  docker push 180169423799.dkr.ecr.us-east-1.amazonaws.com/demo-project:$GITHUB_REF_NAME-$GITHUB_SHA

                  git clone https://${{secrets.AWS_GITHUB_USER}}:${{secrets.AWS_GITHUB_TOKEN}}@github.com/saiurakrishna/gitops-k8s.git

                  cd gitops-k8s

                  git config user.name "saiurakrishna"
                  git config user.email "saikrishna.ura@gmail.com"

                  yq e '.spec.template.spec.containers[0].image = "180169423799.dkr.ecr.us-east-1.amazonaws.com/demo-project:${{ env.GITHUB_BRANCH }}" ' -i deployment.apps/nodejs.yaml

                  git add .
                  git commit -m "update the code"
                  git push --set-upstream origin main
